### ISSUE TITLE
Error in test_davis16.sh

### ISSUE THREAD

**Issue by Deepanshu-beep** [JingchunCheng/FAVOS#5]
@JingchunCheng following is the error I'm receiving on Running the bash:

<_io.TextIOWrapper name='<stderr>' mode='w' encoding='UTF-8'> loading ../data/DAVIS2016//JPEGImages/480p/blackswan/00000.jpg
<_io.TextIOWrapper name='<stderr>' mode='w' encoding='UTF-8'> box num = 246
F1119 18:42:55.289429  1572 im2col.cu:61] Check failed: error == cudaSuccess (48 vs. 0)  no kernel image is available for execution on the device
*** Check failure stack trace: ***
Aborted (core dumped)

**Comment by JingchunCheng** [comment]
It might due to CUDA version incompatibility.
You need to check your cuda and see if it supports your GPU version. 
















At 2020-11-20 02:46:27, "Deepanshu Khanna" <notifications@github.com> wrote:

@JingchunCheng following is the error I'm receiving on Running the bash:

<_io.TextIOWrapper name='' mode='w' encoding='UTF-8'> loading ../data/DAVIS2016//JPEGImages/480p/blackswan/00000.jpg
<_io.TextIOWrapper name='' mode='w' encoding='UTF-8'> box num = 246
F1119 18:42:55.289429 1572 im2col.cu:61] Check failed: error == cudaSuccess (48 vs. 0) no kernel image is available for execution on the device
*** Check failure stack trace: ***
Aborted (core dumped)

**Comment by Deepanshu-beep** [comment]
@JingchunCheng could you please mention the original CUDA version, on which you executed the code. I'll try executing on the same version.

**Comment by JingchunCheng** [comment]
I think the original version is cuda 8.0 with TitanX GPU.
But the code runs well with ubuntu18.04+cuda10.2 on my current environment.


You can just pull a docker which has compiled pycaffe and changes the caffe directory to it. 













At 2020-11-23 19:13:02, "Deepanshu Khanna" <notifications@github.com> wrote:

@JingchunCheng could you please mention the original CUDA version, on which you executed the code. I'll try executing on the same version.

**Comment by Deepanshu-beep** [comment]
@JingchunCheng Okay, Thanks for your support 👍🏻
